// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYTu6i_WG3G8JsaMo5EivyGbV7nbBiH2w',
    appId: '1:995498255998:web:16b3c2d5b8ace733eada2f',
    messagingSenderId: '995498255998',
    projectId: 'fir-flutter-codelab-5bdb4',
    authDomain: 'fir-flutter-codelab-5bdb4.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-5bdb4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3Dadcp7erdEQWtpMNaiN36VAFy08wLes',
    appId: '1:995498255998:android:a14b0377b435f561eada2f',
    messagingSenderId: '995498255998',
    projectId: 'fir-flutter-codelab-5bdb4',
    storageBucket: 'fir-flutter-codelab-5bdb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlCQUOLUSQhuLZVeN06SAbPZ6YJh7r4fI',
    appId: '1:995498255998:ios:5cae19e8d82aec52eada2f',
    messagingSenderId: '995498255998',
    projectId: 'fir-flutter-codelab-5bdb4',
    storageBucket: 'fir-flutter-codelab-5bdb4.appspot.com',
    iosClientId: '995498255998-6hjm6rjdiguij8hgsklc4etq1si7i0vm.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlCQUOLUSQhuLZVeN06SAbPZ6YJh7r4fI',
    appId: '1:995498255998:ios:5cae19e8d82aec52eada2f',
    messagingSenderId: '995498255998',
    projectId: 'fir-flutter-codelab-5bdb4',
    storageBucket: 'fir-flutter-codelab-5bdb4.appspot.com',
    iosClientId: '995498255998-6hjm6rjdiguij8hgsklc4etq1si7i0vm.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
